### ISSUE TITLE
Big todo list

### ISSUE THREAD

**Issue by icambron** [icambron/luxon#3]
# After Node 8.0
 - [x] Remove Intl polyfill
 - [x] Simplify test infra
 - [x] Fix existing tests
 - [x] Add elided tests
 - [x] Rip out fake zones
 - [x] Add formatToParts version of dezoner
 - [x] Fix formatting for IANA zones
- [ ] differentiate L vs M correctly
- [x] Sort out number and calendar settings
- [x] Instant metaformats with zones
- [x] eras 
- [x] unhack offset name stuff
- [x] hardcoded English strings (also use them from the RFC parser!)

# General stuff
- [x] clean up `fromObject` interface (zone stuff, mostly)
- [x] clean up `fromISO` interface (zone stuff, mostly)
- [x] clean up `fromString` interface (zone stuff, mostly)
- [x] unit aliasing
- [x] settings class
- [x] weeks and weekyears (and matching ISO format)
- [x] day of year (and matching ISO format)
- [x] RFC 2822 parsing
- [x] RFC 2822 formatting
- [x] HTTP date parsing
- [x] HTTP date formatting
- [ ] error handling
- [x] Add/subtract for weeks?

# Obvious perf issues

 - [ ] Do some really basic profiling

# Invalid

- [x] contagious invalidity
- [x] tests for invalid instances
- [ ] optional throw on invalid

# Zones
- [x] add `local` and `utc` factory methods
- [x]  clean up `utc`/`utcOffset`/`rezone` conversion functions (use `normalizeZone`)
- [x] better zone testing

#  Intervals
 - [x] Formatter
 - [x] ISO Parser
 - [x] toISO
 - [x] toString
 - [x] locale and similar parity functions 

# Durations
- [x] ISO parser
- [x] toString
- [x] Fix ISO formatting for negative duration parts

# Documentation
 - [ ] Install
 - [ ] Zones/Offsets
 - [ ] Feature support matrix
 - [ ] Intl
 - [ ] Output calendar
 - [ ] Tokens

# Packaging
 - [ ] Bower
 - [ ] Webpack
 - [ ] Require.js
 - [ ] Browserify
 - [ ] System.js
 - [ ] Meteor

# Build
 - [x] Tests for CI
 - [x] Fix CI to use ICU build of Node
 - [ ] Fail build on doc warnings
 - [ ] Site w/docs build and distribution files

# Demo
 - [x] Simple script inclusion
 - [x] Require
